config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products

  root 'homes#index'
  get 'carts/:id' => 'carts#show', as: :cart
  post 'carts' => 'carts#index'
  post 'line_items' => 'products#line_item_create'
  post 'order_complete' => 'carts#order_complete'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user

  validates :user, presence: true

  def subtotal
  	line_items.to_a.sum { |item| item.total_price }
  end

  def add_item(product_id)
  	current_item = line_items.find_by(product_id: product_id)

  	if current_item
  		current_item.quantity += 1
  	else 
  		current_item = line_items.build(product_id: product_id)
  	end
  	current_item
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  validates :cart, :product, presence: true

  def total_price
  	item.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
	validates :name, presence: true
	validates :quantity, presence: true
	validates :quantity, numericality: { greater_than_or_equal_to: 0 }
	validates :price, format: { with: /\A\d+\.?\d{0,2}\z/ }
	validates :description, presence: true
	validates :email, presence: true, format: { with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9\.-]+\.[A-Za-z]+\Z/ }

	has_many :line_items
	before_destroy :ensure_not_referenced_by_any_line_item

	def self.promoted
		where(promoted: true)
	end

	private

	def ensure_not_reference_by_any_line_item
		if line_items.empty?
			return true
		else
			errors.add(:base, 'Line Items present')
			return false
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  has_one :cart

  def self.admin
  	where(admin: true)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  	@cart = Cart.find(params[:id])
  end

  def create
  	@cart = Cart.create(user_id: current_user)
  	if @cart.save
  		redirect_to @cart
  	else
  		redirect_to request.referrer
  	end
  end

  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    redirect_to root_path, notice: 'Your cart is currently empty.'
  end

  def order_complete
    @cart = Cart.find(params[:cart_id])
    @amount = (@cart.subtotal.to_f.round(2) * 100).to_i
    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card => params[:stripeToken]
    )
    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'Wally World customer',
      :currency => 'usd'
    )
      @cart.destroy
     
    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end
end

app/controllers/concerns/current_cart.rb
module CurrentCart
	private
		def find_cart
			@cart = Cart.find(session[:cart_id])
		rescue ActiveRecord::RecordNotFound
			@cart = Cart.create(user_id: current_user.id)
			session[:cart_id] = @cart.id
		end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  	@products = Product.promoted
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
include CurrentCart
before_action :find_cart, only: [:line_item_create]
before_action :authenticate_user!
# before_action :check_for_admin

  def new
  	@product = Product.new
  end

  def index
    @products = Product.all
  end

  def show
  	@product = Product.find(params[:id])
  end

  def edit
  	@product = Product.find(params[:id])
  end

  def create
  	@product = Product.create(product_params)
  	if @product.save
  		redirect_to @product
  	else
  		render :new
  	end
  end

  def update
  	@product = Product.find(params[:id])
  	@product.update(product_params)
  		if @product.save
  			redirect_to @product
  		else
  			render :edit
  		end
  end

  def destroy
  	@product = Product.find(params[:id])
  	@product.destroy
  	redirect_to products_path
  end

  def line_item_create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)
    if @line_item.save
      redirect_to cart_path(@line_item.cart)
    else
      redirect_to @product
    end
  end

  private

  def line_item_params
    params.require(:line_item).permit(:cart_id, :product_id)
  end

  # def check_for_admin
  # 	unless current_user.admin?
  # 		redirect_to root_path
  # 	end
  # end
  def product_params
  	params.require(:product).permit(:name, :quantity, :price, :description, :promoted, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/order_complete.html.erb
<h2>Thank you for your order</h2>

<h5>
	Order # <%= @cart.id %> will be shipping to you, <%= @cart.user.email %> as soon as possible.
</h5>

app/views/carts/show.html.erb
<h2>Your Shopping Cart</h2>
<table class="table">
  <thead>
    <tr>
      <th>Product</th>
      <th>Quantity</th>
      <th>Unit Price</th>
      <th>Total Price</th>
    </tr>
  </thead>
  <tbody>
    <% @cart.line_items.each do |item| %>
      <tr>
        <td><%= item.product.name %></td>
        <td><%= item.quantity %> ×</td>
        <td><%= number_to_currency item.product.price %></td>
        <td><%= number_to_currency item.total_price %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<h3>Order Subtotal:  <%= number_to_currency @cart.subtotal %></h3>
<%= link_to "Continue Shopping", root_path, class: "btn btn-success btn-sm" %>
<%= button_to "Empty Cart", @cart, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-sm", form: {style: 'display:inline-block;'} %>

<div style = 'display:inline-block;'>
  <%= form_tag order_complete_path do %>
    <div>
      <%= hidden_field_tag :cart_id, @cart.id %>
    </div>
    <script src="https://checkout.stripe.com/checkout.js"
    class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="Order #<%= @cart.id %>"
    data-amount="<%= (@cart.subtotal.to_f.round(2) * 100) %>"></script>
  <% end %>
</div>

app/views/homes/index.html.erb
<h1>Home is wherever I'm with you</h1>

<div class="row">
	<% @products.each do |product| %>
		<div class="col-xs-4">
			<div class="panel panel-default">
				<div class="panel-body">
					<p><a href="#" data-toggle="modal" data-target="#myModal_<%= product.id %>"><span class="glyphicon glyphicon-plus"></span>Quick Info</a></p>
					<p><strong><%= number_to_currency product.price %></strong></p>
					<p><%= product.name %></p>
					<div style="height:150px;">
						<p><%= product.description %></p>
					</div>
				</div>
			</div>
		</div>
		<div class="modal fase" id="myModal_<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						<h4 class="modal-title" id="myModalLabel"><%= product.name %></h4>
					</div>
					<div class="modal-body">
						<p><%= number_to_currency product.price %></p>
						<p><%= product.description %></p>
					</div>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<h1>Inventory</h1>

<div class="table-responsive">
	<table class="table table-bordered">
		<tr>
			<th>Name</th>
			<th>Quantity</th>
			<th>Description</th>
			<th>Price</th>
		</tr>
		<% @products.each do |product| %>
		<tr>
			<td><%= link_to product.name, product_path(product) %></td>
			<td><%= product.quantity %></td>
			<td><%= product.description %></td>
			<td><%= product.price %></td>
		</tr>
		<% end %>
	</table>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= form_for @product do |f| %>
  <%= f.text_field :name, class: 'form-control', placeholder: 'Product Name', autofocus: true %>
  <%= f.text_field :description, class: 'form-control', placeholder: 'Product Description' %>
  <div class='form-horizontal'>
    <%= f.label 'Inventory', class: 'col-sm-2' %>
    <%= f.number_field :quantity, class: 'form-control', placeholder: 10, class: 'col-sm-2' %>
  </div>
  <br />
  <br />
  <div class='form-horzontal'>
    <%= f.label :price, class: 'col-sm-2' %>
    <%= f.number_field :price, class: 'form-control', placeholder: 10.00, class: 'col-sm-2', step: 0.01 %><br />
  </div>
  <%= f.submit %>
<% end %>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>

<%= button_to 'Add to Cart', line_items_path(product_id: @product), class: 'btn btn-success' %>